/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_ingreso_pagos;
import clases.cl_ingresos;
import clases.cl_productos_ingresos;
import clases.cl_varios;
import clases_varios.Configuracion;
import forms.frm_reg_ingreso;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import comercial.frm_principal;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author luis
 */
public class frm_ver_ingresos extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();
    cl_ingresos c_ingreso = new cl_ingresos();
    cl_productos_ingresos c_detalle = new cl_productos_ingresos();
    cl_ingreso_pagos c_ingreso_pagos = new cl_ingreso_pagos();

    int fila_seleccionada;
    String query;

    public frm_ver_ingresos() {
        initComponents();

        this.getContentPane().setBackground(Configuracion.COLOR_FORMULARIO_1);
        String periodo = c_varios.obtener_periodo();
        query = "select i.id_ingreso, i.fecha, p.nro_documento, p.razon_social, ds.abreviado, i.serie, i.numero, i.total, u.username, i.tpagado   "
                + "from ingresos as i "
                + "inner join proveedor as p on p.id_proveedor = i.id_proveedor "
                + "inner join documentos_sunat as ds on ds.id_tido = i.id_tido "
                + "inner join usuarios as u on u.id_usuarios = i.id_usuarios "
                + "where concat(year(i.fecha), lpad(month(i.fecha), 2, 0)) = '" + periodo + "' "
                + "order by i.fecha desc, i.numero asc ";
        //c_ingreso.mostrar(t_ingresos, query);
        cargar_tabla();
        sumar_totales();
        t_ingresos.setDefaultRenderer(Object.class, new CeldaColor());
        jd_ver_pagos.getContentPane().setBackground(Configuracion.COLOR_FORMULARIO_1);
        
    }
    private void verificar_deuda() {
        double total = Double.parseDouble(t_ingresos.getValueAt(fila_seleccionada, 5) + "");
        double pagado = Double.parseDouble(t_ingresos.getValueAt(fila_seleccionada, 6) + "");
        
        double total_compra = Double.parseDouble(t_ingresos.getValueAt(fila_seleccionada, 5).toString());
        double total_pagos = 0;
        int filas_pagos = t_pagos.getRowCount();
        for (int i = 0; i < filas_pagos; i++) {
            total_pagos += Double.parseDouble(t_pagos.getValueAt(i, 2).toString());
        }
        
        if (total-pagado != 0) {
            btn_pago_agregar.setEnabled(true);
        } else {
            btn_pago_agregar.setEnabled(false);
        }
    }
    
    private void cargar_tabla() {
        c_ingreso.mostrar(t_ingresos, query);
        int total_compras = t_ingresos.getRowCount();
        double suma_deuda = 0;
        for (int i = 0; i < total_compras; i++) {
            suma_deuda += Double.parseDouble(t_ingresos.getValueAt(i, 6).toString());
        }
        lbl_total_deuda.setText(c_varios.formato_totales(suma_deuda));
    }
    private void activar_botones() {
        btn_detalle.setEnabled(true);
        btn_pdf.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_pagos.setEnabled(true);
    }

    private void desactivar_botones() {
        btn_detalle.setEnabled(false);
        btn_pdf.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_pagos.setEnabled(false);
    }

    private void sumar_totales() {
        int nrofilas = t_ingresos.getRowCount();
        double totales = 0;
        for (int i = 0; i < nrofilas; i++) {
            totales += Double.parseDouble(t_ingresos.getValueAt(i, 5).toString());
        }
        txt_tot_ingresos.setText(c_varios.formato_totales(totales));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_detalle = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_detalle = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_proveedor = new javax.swing.JTextField();
        txt_documento = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        jd_ver_pagos = new javax.swing.JDialog();
        jToolBar2 = new javax.swing.JToolBar();
        btn_pago_agregar = new javax.swing.JButton();
        btn_pago_eliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_pago_salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_pago_documento = new javax.swing.JTextField();
        txt_pago_proveedor = new javax.swing.JTextField();
        txt_pago_fecha = new javax.swing.JTextField();
        txt_pago_total = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_pagos = new javax.swing.JTable();
        jd_reg_pago = new javax.swing.JDialog();
        jToolBar3 = new javax.swing.JToolBar();
        btn_reg_agregar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_reg_salir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_registrar_monto = new javax.swing.JTextField();
        txt_registrar_fecha = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_ingresos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        cbx_buscar = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btn_agregar = new javax.swing.JButton();
        btn_detalle = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        btn_pagos = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_cerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_tot_ingresos = new javax.swing.JTextField();
        txt_fec_inicio = new javax.swing.JFormattedTextField();
        txt_fec_fin = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_total_deuda = new javax.swing.JTextField();

        jd_detalle.setTitle("Ver Detalle de Ingreso de Mercaderia");

        t_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_detalle);

        jLabel2.setText("Proveedor:");

        jLabel3.setText("Documento:");

        jLabel4.setText("Fecha:");

        javax.swing.GroupLayout jd_detalleLayout = new javax.swing.GroupLayout(jd_detalle.getContentPane());
        jd_detalle.getContentPane().setLayout(jd_detalleLayout);
        jd_detalleLayout.setHorizontalGroup(
            jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(jd_detalleLayout.createSequentialGroup()
                        .addGroup(jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_detalleLayout.createSequentialGroup()
                                .addComponent(txt_documento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_proveedor))))
                .addContainerGap())
        );
        jd_detalleLayout.setVerticalGroup(
            jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_ver_pagos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_ver_pagos.setTitle("Ver Pago de Documento de Compra");
        jd_ver_pagos.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setFloatable(false);

        btn_pago_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_pago_agregar.setText("Agregar");
        btn_pago_agregar.setEnabled(false);
        btn_pago_agregar.setFocusable(false);
        btn_pago_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pago_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pago_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pago_agregarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_pago_agregar);

        btn_pago_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_pago_eliminar.setText("Eliminar");
        btn_pago_eliminar.setEnabled(false);
        btn_pago_eliminar.setFocusable(false);
        btn_pago_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pago_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pago_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pago_eliminarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_pago_eliminar);
        jToolBar2.add(jSeparator4);

        btn_pago_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_pago_salir.setText("Salir");
        btn_pago_salir.setFocusable(false);
        btn_pago_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pago_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pago_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pago_salirActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_pago_salir);

        jLabel6.setText("Documento:");

        jLabel7.setText("Proveedor:");

        jLabel8.setText("Fecha.");

        jLabel9.setText("Total:");

        txt_pago_documento.setEditable(false);
        txt_pago_documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_pago_proveedor.setEditable(false);

        txt_pago_fecha.setEditable(false);
        txt_pago_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_pago_total.setEditable(false);
        txt_pago_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        t_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_pagosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(t_pagos);

        javax.swing.GroupLayout jd_ver_pagosLayout = new javax.swing.GroupLayout(jd_ver_pagos.getContentPane());
        jd_ver_pagos.getContentPane().setLayout(jd_ver_pagosLayout);
        jd_ver_pagosLayout.setHorizontalGroup(
            jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pago_proveedor)
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_pago_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pago_total, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 112, Short.MAX_VALUE))))
                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pago_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_ver_pagosLayout.setVerticalGroup(
            jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pago_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pago_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pago_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pago_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_reg_pago.setTitle("Agregar Pago");

        jToolBar3.setFloatable(false);

        btn_reg_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_reg_agregar.setText("Agregar");
        btn_reg_agregar.setEnabled(false);
        btn_reg_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reg_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_reg_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_agregarActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_reg_agregar);
        jToolBar3.add(jSeparator5);

        btn_reg_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_reg_salir.setText("Salir");
        btn_reg_salir.setFocusable(false);
        btn_reg_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reg_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_reg_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_salirActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_reg_salir);

        jLabel10.setText("Fecha.");

        jLabel11.setText("Monto:");

        txt_registrar_monto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_registrar_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_registrar_montoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_registrar_montoKeyPressed(evt);
            }
        });

        try {
            txt_registrar_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_registrar_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_registrar_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_registrar_fechaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jd_reg_pagoLayout = new javax.swing.GroupLayout(jd_reg_pago.getContentPane());
        jd_reg_pago.getContentPane().setLayout(jd_reg_pagoLayout);
        jd_reg_pagoLayout.setHorizontalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_registrar_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(txt_registrar_monto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_reg_pagoLayout.setVerticalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_registrar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_registrar_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setTitle("Ver Ingresos");

        t_ingresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"201810-001", "15/10/2018", "FT / 001-00002451", "10469932091 | OYANGUREN GIRON LUIS ENRIQUE", "loyagureng"},
                {"201810-002", "17/10/2018", "BL / 002-00326541", "10718449559 | DE LA CRUZ ESPINOZA ANDREA TATIANA", "loyangureng"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID.", "Fecha", "Documento", "Proveedor", "Usuario"
            }
        ));
        t_ingresos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_ingresos.setShowHorizontalLines(false);
        t_ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_ingresosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_ingresos);
        if (t_ingresos.getColumnModel().getColumnCount() > 0) {
            t_ingresos.getColumnModel().getColumn(0).setPreferredWidth(100);
            t_ingresos.getColumnModel().getColumn(1).setPreferredWidth(100);
            t_ingresos.getColumnModel().getColumn(2).setPreferredWidth(150);
            t_ingresos.getColumnModel().getColumn(3).setPreferredWidth(450);
            t_ingresos.getColumnModel().getColumn(4).setPreferredWidth(150);
        }

        jLabel1.setText("Buscar por:");

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
        });

        cbx_buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR OPCION", "PERIODO", "FECHAS", "PROVEEDOR", "NRO DOCUMENTO" }));
        cbx_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_buscarActionPerformed(evt);
            }
        });
        cbx_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_buscarKeyPressed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_agregar);

        btn_detalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blog.png"))); // NOI18N
        btn_detalle.setText("Ver Detalle");
        btn_detalle.setEnabled(false);
        btn_detalle.setFocusable(false);
        btn_detalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_detalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detalleActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_detalle);

        btn_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exportar.png"))); // NOI18N
        btn_pdf.setText("Ver PDF");
        btn_pdf.setEnabled(false);
        btn_pdf.setFocusable(false);
        btn_pdf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pdf.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_pdf);

        btn_pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coins.png"))); // NOI18N
        btn_pagos.setText("Ver Pagos");
        btn_pagos.setEnabled(false);
        btn_pagos.setFocusable(false);
        btn_pagos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pagos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagosActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_pagos);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setEnabled(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_eliminar);
        jToolBar1.add(jSeparator1);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cerrar);

        jLabel5.setText("Suma Ingresos:");

        txt_tot_ingresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot_ingresos.setText("0.00");

        try {
            txt_fec_inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_inicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_inicio.setEnabled(false);
        txt_fec_inicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_inicioKeyPressed(evt);
            }
        });

        try {
            txt_fec_fin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_fin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_fin.setEnabled(false);
        txt_fec_fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_finKeyPressed(evt);
            }
        });

        jLabel12.setText("Total Pagado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fec_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fec_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tot_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_total_deuda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_tot_ingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fec_inicio)
                        .addComponent(txt_fec_fin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_deuda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        this.dispose();
        frm_reg_ingreso formulario = new frm_reg_ingreso();
        c_varios.llamar_ventana(formulario);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String buscar = txt_buscar.getText().trim();
            int tipo_busqueda = cbx_buscar.getSelectedIndex();

            if (tipo_busqueda == 0) {
                query = "select i.id_ingreso, i.fecha, p.nro_documento, p.razon_social, ds.abreviado, i.serie, i.numero, i.total, u.username "
                        + "from ingresos as i "
                        + "inner join proveedor as p on p.id_proveedor = i.id_proveedor "
                        + "inner join documentos_sunat as ds on ds.id_tido = i.id_tido "
                        + "inner join usuarios as u on u.id_usuarios = i.id_usuarios "
                        + "where concat(year(i.fecha), LPAD(month(i.fecha), 2, 0)) = '" + buscar + "' "
                        + "order by i.fecha asc, i.numero asc";
            }

            if (tipo_busqueda == 1) {
                // buscar fechas con rango 
                buscar = c_varios.fecha_myql(buscar);
                query = "select i.id_ingreso, i.fecha, p.nro_documento, p.razon_social, ds.abreviado, i.serie, i.numero, i.total, u.username "
                        + "from ingresos as i "
                        + "inner join proveedor as p on p.id_proveedor = i.id_proveedor "
                        + "inner join documentos_sunat as ds on ds.id_tido = i.id_tido "
                        + "inner join usuarios as u on u.id_usuarios = i.id_usuarios "
                        + "where i.fecha = '" + buscar + "' "
                        + "order by i.numero asc";
            }

            if (tipo_busqueda == 2) {
                query = "select i.id_ingreso, i.fecha, p.nro_documento, p.razon_social, ds.abreviado, i.serie, i.numero, i.total, u.username "
                        + "from ingresos as i "
                        + "inner join proveedor as p on p.id_proveedor = i.id_proveedor "
                        + "inner join documentos_sunat as ds on ds.id_tido = i.id_tido "
                        + "inner join usuarios as u on u.id_usuarios = i.id_usuarios "
                        + "where p.nro_documento = '" + buscar + "' or p.razon_social like '%" + buscar + "%' "
                        + "order by i.fecha asc";
            }
            if (tipo_busqueda == 3) {
                query = "select i.id_ingreso, i.fecha, p.nro_documento, p.razon_social, ds.abreviado, i.serie, i.numero, i.total, u.username "
                        + "from ingresos as i "
                        + "inner join proveedor as p on p.id_proveedor = i.id_proveedor "
                        + "inner join documentos_sunat as ds on ds.id_tido = i.id_tido "
                        + "inner join usuarios as u on u.id_usuarios = i.id_usuarios "
                        + "where i.numero = '" + buscar + "' "
                        + "order by i.fecha asc";
            }
            c_ingreso.mostrar(t_ingresos, query);
            sumar_totales();
        }
    }//GEN-LAST:event_txt_buscarKeyPressed

    private void cbx_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_buscarActionPerformed
        int opcion = cbx_buscar.getSelectedIndex();
        switch (opcion) {
            case 1:
                txt_fec_inicio.setEnabled(false);
                txt_fec_fin.setEnabled(false);
                txt_buscar.setEnabled(true);
                txt_buscar.selectAll();
                txt_buscar.requestFocus();
                break;
            case 2:
                txt_fec_inicio.setEnabled(true);
                txt_fec_fin.setEnabled(true);
                txt_buscar.setEnabled(false);
                txt_fec_inicio.requestFocus();
                break;
            case 4:
                txt_fec_inicio.setEnabled(false);
                txt_fec_fin.setEnabled(false);
                txt_buscar.setEnabled(true);
                txt_buscar.selectAll();
                txt_buscar.requestFocus();
                break;
            case 3:
                txt_fec_inicio.setEnabled(false);
                txt_fec_fin.setEnabled(false);
                txt_buscar.setEnabled(true);
                txt_buscar.selectAll();
                txt_buscar.requestFocus();
                break;
            default:
                break;
        }

    }//GEN-LAST:event_cbx_buscarActionPerformed

    private void t_ingresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_ingresosMouseClicked
        if (evt.getClickCount() == 2) {
            activar_botones();
            fila_seleccionada = t_ingresos.getSelectedRow();
            c_ingreso.setId_ingreso(Integer.parseInt(t_ingresos.getValueAt(fila_seleccionada, 0).toString()));
            c_detalle.setId_ingreso(c_ingreso.getId_ingreso());
        }
    }//GEN-LAST:event_t_ingresosMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        frm_principal.c_permiso.setId_permiso(5);
        boolean permitido = frm_principal.c_permiso.validar();

        if (permitido) {
            if (fila_seleccionada > -1) {
                int confirmado = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Eliminar el Documento de Ingreso de Mercaderia?");
                desactivar_botones();

                if (JOptionPane.OK_OPTION == confirmado) {
                    c_detalle.setId_ingreso(c_ingreso.getId_ingreso());
                    c_detalle.eliminar();
                    c_ingreso.eliminar();

                    c_ingreso.mostrar(t_ingresos, query);
                    sumar_totales();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No ha seleccionado una fila");

            }
        } else {
            JOptionPane.showMessageDialog(null, "Usted no tiene permiso para realizar esta operacion!!");
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detalleActionPerformed
        desactivar_botones();
        jd_detalle.setModal(true);
        jd_detalle.setSize(900, 600);
        jd_detalle.setLocationRelativeTo(null);
        txt_proveedor.setText(t_ingresos.getValueAt(fila_seleccionada, 3).toString());
        txt_documento.setText(t_ingresos.getValueAt(fila_seleccionada, 2).toString());
        txt_fecha.setText(t_ingresos.getValueAt(fila_seleccionada, 1).toString());
        c_detalle.mostrar_detalle(t_detalle);
        jd_detalle.setVisible(true);
    }//GEN-LAST:event_btn_detalleActionPerformed

    private void cbx_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_buscar.selectAll();
            txt_buscar.requestFocus();
        }
    }//GEN-LAST:event_cbx_buscarKeyPressed

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void txt_fec_inicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_inicioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_inicio.getText().length() == 10) {
                txt_fec_fin.setEnabled(true);
                txt_fec_fin.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fec_inicioKeyPressed

    private void txt_fec_finKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_finKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_inicio.getText().length() == 10) {
                txt_fec_fin.setEnabled(true);
                txt_fec_fin.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fec_finKeyPressed

    private void btn_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagosActionPerformed
        desactivar_botones();
        txt_pago_documento.setText(t_ingresos.getValueAt(fila_seleccionada, 2).toString());
        txt_pago_fecha.setText(t_ingresos.getValueAt(fila_seleccionada,1).toString());
        txt_pago_proveedor.setText(t_ingresos.getValueAt(fila_seleccionada, 3).toString());
        txt_pago_total.setText(t_ingresos.getValueAt(fila_seleccionada, 5).toString());
        int idIngreso = Integer.parseInt(t_ingresos.getValueAt(fila_seleccionada, 0).toString());
        c_ingreso_pagos.setId_ingreso(idIngreso);
        c_ingreso_pagos.mostrar(t_pagos);

        verificar_deuda();

        jd_ver_pagos.setModal(true);
        jd_ver_pagos.setSize(400, 494);
        jd_ver_pagos.setLocationRelativeTo(null);
        jd_ver_pagos.setVisible(true);
    }//GEN-LAST:event_btn_pagosActionPerformed

    private void btn_pago_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pago_agregarActionPerformed
        txt_registrar_fecha.setText(c_varios.fecha_usuario(c_varios.getFechaActual()));
        jd_reg_pago.setModal(true);
        jd_reg_pago.setSize(295, 186);
        jd_reg_pago.setLocationRelativeTo(null);
        jd_reg_pago.setVisible(true);
        txt_registrar_monto.requestFocus();
    }//GEN-LAST:event_btn_pago_agregarActionPerformed

    private void btn_pago_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pago_eliminarActionPerformed
        btn_pago_eliminar.setEnabled(false);
        int confirmado = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Eliminar el Pago?");

       if (JOptionPane.OK_OPTION == confirmado) {
            c_ingreso_pagos.eliminar();
            c_ingreso_pagos.mostrar(t_pagos);
            verificar_deuda();
        }
    }//GEN-LAST:event_btn_pago_eliminarActionPerformed

    private void btn_pago_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pago_salirActionPerformed
        jd_ver_pagos.dispose();
        cargar_tabla();
    }//GEN-LAST:event_btn_pago_salirActionPerformed

    private void t_pagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_pagosMouseClicked
        int fila_pago = t_pagos.getSelectedRow();
        btn_pago_eliminar.setEnabled(true);
        c_ingreso_pagos.setId_ingreso_pago(Integer.parseInt(t_pagos.getValueAt(fila_pago, 0).toString()));
    }//GEN-LAST:event_t_pagosMouseClicked

    private void btn_reg_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_agregarActionPerformed
        c_ingreso_pagos.setFecha(c_varios.fecha_myql(txt_registrar_fecha.getText()));
        c_ingreso_pagos.setMonto(Double.parseDouble(txt_registrar_monto.getText()));
        c_ingreso_pagos.obtener_codigo();
        if (c_ingreso_pagos.registrar()) {
            btn_reg_salir.doClick();
        }
    }//GEN-LAST:event_btn_reg_agregarActionPerformed

    private void btn_reg_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_salirActionPerformed
        jd_reg_pago.dispose();
        c_ingreso_pagos.mostrar(t_pagos);
        verificar_deuda();
    }//GEN-LAST:event_btn_reg_salirActionPerformed

    private void txt_registrar_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_registrar_montoKeyTyped
        c_varios.solo_precio(evt);
        c_varios.limitar_caracteres(evt, txt_registrar_monto, 10);
    }//GEN-LAST:event_txt_registrar_montoKeyTyped

    private void txt_registrar_montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_registrar_montoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String numero = txt_registrar_monto.getText();
            if (c_varios.esDecimal(numero)) {
                btn_reg_agregar.setEnabled(true);
                btn_reg_agregar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_registrar_montoKeyPressed

    private void txt_registrar_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_registrar_fechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_registrar_monto.requestFocus();
        }
    }//GEN-LAST:event_txt_registrar_fechaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_detalle;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_pago_agregar;
    private javax.swing.JButton btn_pago_eliminar;
    private javax.swing.JButton btn_pago_salir;
    private javax.swing.JButton btn_pagos;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JButton btn_reg_agregar;
    private javax.swing.JButton btn_reg_salir;
    private javax.swing.JComboBox<String> cbx_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JDialog jd_detalle;
    private javax.swing.JDialog jd_reg_pago;
    private javax.swing.JDialog jd_ver_pagos;
    private javax.swing.JTextField lbl_total_deuda;
    private javax.swing.JTable t_detalle;
    private javax.swing.JTable t_ingresos;
    private javax.swing.JTable t_pagos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JFormattedTextField txt_fec_fin;
    private javax.swing.JFormattedTextField txt_fec_inicio;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_pago_documento;
    private javax.swing.JTextField txt_pago_fecha;
    private javax.swing.JTextField txt_pago_proveedor;
    private javax.swing.JTextField txt_pago_total;
    private javax.swing.JTextField txt_proveedor;
    private javax.swing.JFormattedTextField txt_registrar_fecha;
    private javax.swing.JTextField txt_registrar_monto;
    private javax.swing.JTextField txt_tot_ingresos;
    // End of variables declaration//GEN-END:variables
}

class CeldaColor extends DefaultTableCellRenderer {

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected,
            boolean hasFocus,
            int row,
            int column) {

        double total = Double.parseDouble(table.getValueAt(row, 5) + "");
        double pagado = Double.parseDouble(table.getValueAt(row, 6) + "");
        setBackground(Color.WHITE);
        setForeground(Color.BLACK);
        
        if (total - pagado != 0) {
            setBackground(Configuracion.COLOR_CELDA_DEUDA);
            setForeground(Configuracion.COLOR_CELDA_TEXT_DEUDA);
        }
        


        return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
    }

}
